config/routes.rb
ScaffoldLinkBlog::Application.routes.draw do
  resources :link_posts

end

app/models/link_post.rb
class LinkPost < ActiveRecord::Base
  attr_accessible :description, :link, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/link_posts_controller.rb
class LinkPostsController < ApplicationController
  # GET /link_posts
  # GET /link_posts.json
  def index
    @link_posts = LinkPost.find(:all, :limit => 5, :order=> 'created_at').reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @link_posts }
    end
  end

  # GET /link_posts/1
  # GET /link_posts/1.json
  def show
    @link_post = LinkPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link_post }
    end
  end

  # GET /link_posts/new
  # GET /link_posts/new.json
  def new
    @link_post = LinkPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link_post }
    end
  end

  # GET /link_posts/1/edit
  def edit
    @link_post = LinkPost.find(params[:id])
  end

  # POST /link_posts
  # POST /link_posts.json
  def create
    @link_post = LinkPost.new(params[:link_post])

    respond_to do |format|
      if @link_post.save
        format.html { redirect_to @link_post, notice: 'Link post was successfully created.' }
        format.json { render json: @link_post, status: :created, location: @link_post }
      else
        format.html { render action: "new" }
        format.json { render json: @link_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /link_posts/1
  # PUT /link_posts/1.json
  def update
    @link_post = LinkPost.find(params[:id])

    respond_to do |format|
      if @link_post.update_attributes(params[:link_post])
        format.html { redirect_to @link_post, notice: 'Link post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_posts/1
  # DELETE /link_posts/1.json
  def destroy
    @link_post = LinkPost.find(params[:id])
    @link_post.destroy

    respond_to do |format|
      format.html { redirect_to link_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_posts_helper.rb
module LinkPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScaffoldLinkBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/link_posts/_form.html.erb
<%= form_for(@link_post) do |f| %>
  <% if @link_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link_post.errors.count, "error") %> prohibited this link_post from being saved:</h2>

      <ul>
      <% @link_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/link_posts/edit.html.erb
<h1>Editing link_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @link_post %> |
<%= link_to 'Back', link_posts_path %>

app/views/link_posts/index.html.erb
<h1>Listing link_posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Link</th>
    <th>Created</th>
    <th></th>
    <th></th>
  </tr>

<% @link_posts.each do |link_post| %>
  <tr>
    <td><%= link_post.title %></td>
    <td><a href="<%= link_post.link %>"><%= link_post.link %></a></td>
    <td><%= link_post.created_at %></td>
    <td><%= link_to 'Show', link_post %></td>
    <td><%= link_to 'Edit', edit_link_post_path(link_post) %></td>
    <td><%= link_to 'Destroy', link_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link post', new_link_post_path %>

app/views/link_posts/new.html.erb
<h1>New link_post</h1>

<%= render 'form' %>

<%= link_to 'Back', link_posts_path %>

app/views/link_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @link_post.title %>
</p>

<p>
  <b>Link:</b>
  <%= @link_post.link %>
</p>

<p>
  <b>Description:</b>
  <%= @link_post.description %>
</p>


<%= link_to 'Edit', edit_link_post_path(@link_post) %> |
<%= link_to 'Back', link_posts_path %>